%Generate and test approach
%perform integer division using addition and subtraction
%N1,N2, Result are assumed to be integers, Result is to be quotient of dividing n1/n2
%is_integer is supposed to generate successive elements of the sequence 0,1,2...


is_integer(0).
is_integer(X) :- is_integer(Y), X is Y + 1. 

divide(N1,N2,Result) :- is_integer(Result),
			Product1 is Result * N2, 
			Product2 is (Result + 1) * N2, 
			Product1 =< N1, Product2 > N1.

%divide(8,2,Result).

%if Result is an integer
%if Product1 is Result * 2  
%if Product2 is Result + 1 * 2
%if Product1 is <= 8 ; is (Result * 2) <= 8? it finds 0, 1,2,3,4 satisfies this 
%if Product2 is > 8 ; is ((Result + 1) * 2 ) > 8? what nums out of 0,1,2,3,4 satisfy this? 4! 
%searches through the list of integers generated by is_integer()... (0 1 2 3....) to find an element that satisifies lines 4 and 5 
